# Generated by Django 4.2 on 2026-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimenotification',
            name='notification_type',
            field=models.CharField(choices=[('new_task', 'Нове завдання'), ('task_update', 'Оновлено завдання'), ('task_due', 'Наближається дедлайн'), ('system', 'Системне повідомлення')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Вхід'), ('logout', 'Вихід'), ('task_create', 'Створення завдання'), ('task_update', 'Оновлення завдання'), ('task_delete', 'Видалення завдання'), ('page_visit', 'Відвідування сторінки')], max_length=20),
        ),
    ]
